FROM ${ROOT_IMAGE}

USER root
RUN DEBIAN_FRONTEND=noninteractive

# Update repositories && system
RUN apt-get clean && apt-get -qq update && apt-get -yqq upgrade

# Install base packages
RUN apt-get clean && apt-get update && \
  apt-get install -yqq --no-install-recommends git-core \
  sudo \
  gcc \
  curl \
  make \
  autoconf \
  automake \
  libtool \
  pkg-config \
  zlib1g-dev \
  build-essential \
  libssl-dev \
  libreadline-dev \
  libyaml-dev \
  libsqlite3-dev \
  sqlite3 \
  libxml2-dev \
  libxslt1-dev \
  libcurl4-openssl-dev \
  software-properties-common \
  libffi-dev \
  python3-dev \
  python3-venv \
  openssh-server \
  jq
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

# install the latest aws-cli
RUN ln -s /usr/bin/python3.7 /usr/bin/python
RUN \
  temp_path=$(mktemp -d); \
  curl https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o ${temp_path}/awscli-bundle.zip \
  && unzip ${temp_path}/awscli-bundle.zip -d ${temp_path} \
  && ${temp_path}/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws \
  && rm -rf ${temp_path} \
  && ln /usr/local/bin/aws /sbin/aws

COPY init.groovy/* /usr/share/jenkins/ref/init.groovy.d/

# Upgrade jenkins

# Use base container's ARGs by default
ARG JENKINS_OVERRIDE_VERSION
ENV JENKINS_OVERRIDE_VERSION=${JENKINS_OVERRIDE_VERSION}
RUN mkdir /var/log/jenkins && chown -R jenkins:jenkins /var/log/jenkins

ENV JENKINS_URL=https://updates.jenkins-ci.org/download/war/${JENKINS_OVERRIDE_VERSION}/jenkins.war
RUN curl -fsSL ${JENKINS_URL} -o /usr/share/jenkins/jenkins.war
# verify jenkins.war
RUN jarsigner -verify -verbose /usr/share/jenkins/jenkins.war

# inject bootstrap script
COPY bootstrap.sh /usr/local/bin/bootstrap.sh
RUN chmod 755 /usr/local/bin/bootstrap.sh

# install libucl
RUN git clone https://github.com/vstakhov/libucl.git \
  && cd libucl \
  && ./autogen.sh \
  && ./configure \
  && make install

# install RUST
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

# install nereond
RUN /root/.cargo/bin/cargo install --git https://github.com/riboseinc/nereond.git

# install riffol
RUN /root/.cargo/bin/cargo install --git https://github.com/riboseinc/riffol.git

# Inject startup script
COPY startup.sh /usr/local/bin/startup.sh
RUN chmod 755 /usr/local/bin/startup.sh

# Let's use root from now on
# Switch back
# USER jenkins

ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/startup.sh"]

